version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - monitoring

  k6:
    image: loadimpact/k6
    volumes:
      - ./loadTest.js:/loadTest.js
    depends_on:
      - app
    command: run /loadTest.js
    networks:
      - monitoring

networks:
  monitoring:
